### ISSUE TITLE
All functions and methods need to be in snake case

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/bioNC#15]
To build a python package, we need to respect some standards:

Every methods needs to be in snake case, for example:

```python3 
def rigidBodyConstraint(...)
```
should be changed into:

```python3 
def rigidbody_constraint(...)
```

**Comment by ANaaim** [comment]
I should be able to tackle this ^^'

**Comment by Ipuch** [comment]
Alright ! For this use refactor of vs studio it will fasten the process 👌🏼
