### ISSUE TITLE
documentation of NaturalSegment need to be up to date

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/bioNC#16]
NaturalSegment docstrings are not up to date, each attribute and method need to be listed.

https://github.com/Ipuch/bioNC/blob/2f081fd10f4acad1ce70c71134710bbc8feab91f/bionc/model_computations/natural_segment.py#L16-L47

**Comment by Ipuch** [comment]
@ANaaim I would give this first issue to Anais, to first understand the mechanism of pull request without any risk to modify code. It would allow her to understand how the whole process works while still contributing to bioNC.

The idea of this pull request is just to detail every method function of the class in the doctstrings and every attributes in Numpy format.

**Comment by ANaaim** [comment]
Ok for me

**Comment by Ipuch** [comment]
@aaiaueil

**Comment by aaiaueil** [comment]
Done for the methods

**Comment by Ipuch** [comment]
looks good to me right now
