### ISSUE TITLE
Joints implementation

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/bioNC#18]
Minimum Joints need to be implemented to handle articulated kinematic chains. A draft has been begun but it needs to interact with the BioemchanicalModel

https://github.com/Ipuch/bioNC/blob/2f081fd10f4acad1ce70c71134710bbc8feab91f/bionc/model_computations/joint.py#L65-L172

**Comment by Ipuch** [comment]
``` 
model.add_joint(
joint=Joint.Hinge, parent="thigh", 
child="shank",
)
```

Do we need more ?

**Comment by ANaaim** [comment]
First approaching of creating a joint seems more logical to me.:
```python
 model.add_joint(
joint=Joint.Hinge, 
parent="thigh", 
child="shank",
)
```

**Comment by Ipuch** [comment]
How should we handle closed kinematic chains, When a segment has two parents ?

**Comment by ANaaim** [comment]
It should not be a problem. In the end, the terminology should only be distal and proximal.

For the kinematics aspect, the proximal and distal decide how to calulate the kinematics.

For the constraint/optimisation, we just need to know the indices of each segment to be able to write the constraint at the correct position in the kinematics constraint matrix.

I think that in my code you can do closed loop however i never tested if it works (i am not studying a lot of closed loop system ;) )

**Comment by Ipuch** [comment]
I agree

I'm raising this to think ahead for inverse dynamics implementation.

**Comment by Ipuch** [comment]
#42 done.
api, need to be enhanced now and it will be fine.
