### ISSUE TITLE
Inverse kinematics as a first milestone

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/bioNC#21]
Once we have this, I think the rest will follow 👌🏼

Inspiration codes:

https://github.com/ANaaim/Kinetics_LBMC/blob/master/Kinetics_LBMC/multi_body_optimisation.py

https://github.com/pyomeca/biorbd/blob/master/binding/python3/rigid_body.py

**Comment by ANaaim** [comment]
To be done : Compare MBO  with Newton-Raphson vs optimisation tool found in other library.
