### ISSUE TITLE
No mass_matrix creation when using SegmentTemplate. 

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/bioNC#96]
When creating a segment in a model using the following : 

```python 
    model["RSHANK"] = SegmentTemplate(
        natural_segment=NaturalSegmentTemplate(
            u_axis=AxisFunctionTemplate(
                function=lambda m, bio: MarkerTemplate.normal_to(m, bio, right_knee_joint(m, bio), "RFAL", "RTAM")
            ),
            proximal_point=right_knee_joint,
            # the knee joint computed from the medial femoral epicondyle and the lateral femoral epicondyle
            distal_point=lambda m, bio: MarkerTemplate.middle_of(m, bio, "RFAL", "RTAM"),
            w_axis=AxisTemplate(start="RTAM", end="RFAL"),
        ),
        inertia_parameters=InertiaParametersTemplate(mass=1,
            center_of_mass=np.array([0, -0.5, 0]),  # in segment coordinates system
            inertia=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

    )
```
The inertia parameters are not given to the natural segment later on. I have the following error later on in the code (in inverse_dynamic class): 
```
  File "----------------------------------------\bioNC\bioNC\bionc\bionc_casadi\natural_segment.py", line 768, in inverse_dynamics
    (self.mass_matrix @ Qddoti)
     ~~~~~~~~~~~~~~~~~^~~~~~~~
```
because self.mass_matrix is None.

Should the segment constructed differently or a specific command should be run for the segmentTemplate to update the different value ?  I saw that for the examples three_link_pendulum.py, you are directly creating natural segment with the inertia properties which is different from creating from c3d data i suppose.

I will continue to investigate ... 🕵️

Thanks

**Comment by ANaaim** [comment]
Ok for me ^^' at least i am not crazy  🤪. 

So it will be nedded if we want to compare result from real analysis. Let's go :)

**Comment by Ipuch** [comment]
A work around can be to set it, after building the model.

For example 

Model.segments["thigh"].mass=xx

**Comment by ANaaim** [comment]
This command generate such error message : 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
AttributeError: property 'mass' of 'NaturalSegment' object has no setter

**Comment by Ipuch** [comment]
I think I can close this as it is an expected behavior.
